### ISSUE TITLE
Issue with ordered and unordered lists

### ISSUE THREAD

**Issue by xfoldvar** [fleetingbytes/rtfparse#38] opened 2024-10-25 14:38 UTC
I just tried your lib and found out that when extracting HTML from the MSG file that contains RTF with ordered/unordered lists, these lists are corrupt / displayed incorrectly.

**Unordered lists:** They have rendered bullets and right after the bullet there is a * character - this should not be present.

**Ordered lists:** Their items are duplicated. See the attached SS. Eg when there is an ordered list like this:

1.  Item

It does look like this:

1.  1.Item

![image](https://github.com/user-attachments/assets/796824e0-7329-44d7-8a90-893f4d1b6cda)

Original MSG file.

[Formátování z Outlook__2024_10_16.zip](https://github.com/user-attachments/files/17523617/Formatovani.z.Outlook__2024_10_16.zip)

**Comment by fleetingbytes** [comment] 2024-10-25 17:37
Wow, this looks like an interesting bug. Thanks for the example file. I no longer have an easy access to a computer with MS Outlook, or other MS Office products, so this will be a bit hard for me to explore and verify a fix.

Also, I am leaving for vacation for the next 11 days. But I will look into this once I am back.

**Comment by fleetingbytes** [comment] 2024-10-28 16:16
Hi @xfoldvar, 

I ran my decapsulator through your .msg file.

This is the excerpt of the ordered and unordered list items from the RTF (I just added some newline characters to make it a bit more readable:

```rtf
{\*\htmltag64 <p class=MsoNormal>}\htmlrtf {
\htmlrtf0 Odr\'e1\'9eky
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0
\htmlrtf \par

\htmlrtf0 
{\*\htmltag72 </p>}
{\*\htmltag96 <ul style='margin-top:0cm' type=disc>}\htmlrtf {
\htmlrtf0 
{\*\htmltag64 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level1 lfo1'>}\htmlrtf {{\*\pn\pnlvlblt\pnf2\pnindent360{\pntxtb\'b7}}
\htmlrtf0 \li360 \fi-360 {\pntext *\tab}Jedna odr\'e1\'9eka
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0

{\*\htmltag72 </li>}
{\*\htmltag96 <ul style='margin-top:0cm' type=circle>}\htmlrtf \par
{
\htmlrtf0 
{\*\htmltag64 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level2 lfo1'>}\htmlrtf {{\*\pn\pnlvlblt\pnf2\pnindent360{\pntxtb\'b7}}
\htmlrtf0 \li720 \fi-360 {\pntext *\tab}Pododr\'e1\'9eka
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0

{\*\htmltag72 </li>}
{\*\htmltag64 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level2 lfo1'>}\htmlrtf {{\*\pn\pnlvlblt\pnf2\pnindent360{\pntxtb\'b7}}
\htmlrtf0 \li720 \fi-360 {\pntext *\tab}Taky pododr\'e1\'9eka
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0

{\*\htmltag72 </li>}
{\*\htmltag104 </ul>}\htmlrtf }\par

\htmlrtf0 
{\*\htmltag64 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level1 lfo1'>}\htmlrtf {{\*\pn\pnlvlblt\pnf2\pnindent360{\pntxtb\'b7}}
\htmlrtf0 \li360 \fi-360 {\pntext *\tab}Druh\'e1 odr\'e1\'9eka
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0

{\*\htmltag72 </li>}
{\*\htmltag64 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level1 lfo1'>}\htmlrtf {{\*\pn\pnlvlblt\pnf2\pnindent360{\pntxtb\'b7}}
\htmlrtf0 \li360 \fi-360 {\pntext *\tab}T\'f8et\'ed odr\'e1\'9eka
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0

{\*\htmltag72 </li>}
{\*\htmltag104 </ul>}\htmlrtf }\par

\htmlrtf0 
{\*\htmltag64 <p class=MsoNormal>}\htmlrtf {
\htmlrtf0 
{\*\htmltag244 <o:p>}
{\*\htmltag84 &nbsp;}\htmlrtf \'a0
\htmlrtf0 
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0
\htmlrtf \par

\htmlrtf0 
{\*\htmltag72 </p>}
{\*\htmltag64 <p class=MsoNormal>}\htmlrtf {
\htmlrtf0 \'c8\'edslov\'e1n\'ed
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0
\htmlrtf \par

\htmlrtf0 
{\*\htmltag72 </p>}
{\*\htmltag96 <ol style='margin-top:0cm' start=1 type=1>}\htmlrtf {
\htmlrtf0 
{\*\htmltag64 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo2'>}\htmlrtf {{\*\pn\pnlvlbody\pndec\pnstart1\pnindent360{\pntxta .}}
\htmlrtf0 \li360 \fi-360 {\pntext 1.\tab}m\'edsto
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0

{\*\htmltag72 </li>}
{\*\htmltag96 <ol style='margin-top:0cm' start=1 type=a>}\htmlrtf \par
{
\htmlrtf0 
{\*\htmltag64 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level2 lfo2'>}\htmlrtf {{\*\pn\pnlvlbody\pnlcltr\pnstart1\pnindent360{\pntxta .}}
\htmlrtf0 \li720 \fi-360 {\pntext a.\tab}Pod\'farove\'f2 A
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0

{\*\htmltag72 </li>}
{\*\htmltag64 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level2 lfo2'>}\htmlrtf {{\*\pn\pnlvlbody\pnlcltr\pnstart2\pnindent360{\pntxta .}}
\htmlrtf0 \li720 \fi-360 {\pntext b.\tab}Pod\'farove\'f2 B
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0

{\*\htmltag72 </li>}
{\*\htmltag104 </ol>}\htmlrtf }\par

\htmlrtf0 
{\*\htmltag64 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo2'>}\htmlrtf {{\*\pn\pnlvlbody\pndec\pnstart2\pnindent360{\pntxta .}}
\htmlrtf0 \li360 \fi-360 {\pntext 2.\tab}m\'edsto
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0

{\*\htmltag72 </li>}
{\*\htmltag64 <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo2'>}\htmlrtf {{\*\pn\pnlvlbody\pndec\pnstart3\pnindent360{\pntxta .}}
\htmlrtf0 \li360 \fi-360 {\pntext 3.\tab}m\'edsto
{\*\htmltag244 <o:p>}
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0

{\*\htmltag72 </li>}
{\*\htmltag104 </ol>}\htmlrtf }\par

\htmlrtf0 
{\*\htmltag64 <p class=MsoNormal>}\htmlrtf {
\htmlrtf0 
{\*\htmltag244 <o:p>}
{\*\htmltag84 &nbsp;}\htmlrtf \'a0
\htmlrtf0 
{\*\htmltag252 </o:p>}\htmlrtf\par}
\htmlrtf0
\htmlrtf \par

\htmlrtf0 
{\*\htmltag72 </p>}
```

And this is how the HTML was decapsulated (here, too, I added newlines and some indentation)
```html
<p class=MsoNormal>Odrážky<o:p></o:p></p>
<ul style='margin-top:0cm' type=disc>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level1 lfo1'>*	Jedna odrážka<o:p></o:p></li>
  <ul style='margin-top:0cm' type=circle>
    <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level2 lfo1'>*	Pododrážka<o:p></o:p></li>
    <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level2 lfo1'>*	Taky pododrážka<o:p></o:p></li>
  </ul>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level1 lfo1'>*	Druhá odrážka<o:p></o:p></li>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l1 level1 lfo1'>*	Třetí odrážka<o:p></o:p></li>
</ul>
<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>Číslování<o:p></o:p></p>
<ol style='margin-top:0cm' start=1 type=1>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo2'>1.	místo<o:p></o:p></li>
  <ol style='margin-top:0cm' start=1 type=a>
    <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level2 lfo2'>a.	Podúroveň A<o:p></o:p></li>
    <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level2 lfo2'>b.	Podúroveň B<o:p></o:p></li>
  </ol>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo2'>2.	místo<o:p></o:p></li>
  <li class=MsoListParagraph style='margin-left:0cm;mso-list:l0 level1 lfo2'>3.	místo<o:p></o:p></li>
</ol>
<p class=MsoNormal><o:p>&nbsp;</o:p></p>
```

The problem is that the html decapsulator outputs the plain text part of the `\pntext` Control Group (`pn` stands for paragraph numbering). The plain text content of the group is `*\tab` which renders to `*` and a tab character in the resulting html file. This is a bug of the decapsulator. Thank you again for the report.

In the RTF code there are many information about the styles of the ordered and unordered lists in a number of control words and groups starting with `\pn` (see pages 84ff of the [RTF specification](https://web.archive.org/web/20190708132914/http://www.kleinlercher.at/tools/Windows_Protocols/Word2007RTFSpec9.pdf)), but this is all information which is absent in the encapsulated html code. Since a decapsulator shall just decapsulate the HTML out of the RTF, I must correct it to ignore any information contained in these `\pn` control groups. It shall not try to enrich the encapsulated HTML code with information from the RTF.

Thus I shall include `\pntext`, `\pntxta`, `\pntxtb`, which are not explicitly marked as ignorable groups to the [tuple of willfully ignored groups](https://github.com/fleetingbytes/rtfparse/blob/db4818b93143231b4c8fb815465cfa433c376ec0/src/rtfparse/renderers/html_decapsulator.py#L31).

A fix is coming out, just give me some time to release it. You can of course fork it and fix it yourself, or even create a pull request, but I will still need some time to review this and make the actual release. Probably some time towards the end of my vacation, or thereafter.

**Comment by xfoldvar** [comment] 2024-10-28 18:07
@fleetingbytes Thanks for the explanation you provided! I can try and play with the decapsulator implementation - if I find some free time to do it, I will send you a PR. Otherwise, I will wait for your fix. Enjoy your vacation!

**Closed** 2024-11-01 08:53 UTC
